import 'package:flutter/material.dart';
import 'book.dart';

// Generalized widget for rendering all the required books

class Shelf extends StatefulWidget {
  @override
  createState() => new ShelfState();
}

class ShelfState extends State<Shelf> {

  List<Book> _books = [];

  void _addBook() {
    //SetState() will rerender the Shelf
    setState(() {
      int index = _books.length;
      _books.add(new Book("Test Book" + index.toString(), "Test Author")); // Autogenerated Test Data
    });
  }

  Widget _buildShelf() {
    return new ListView.builder(
      // ignore: missing_return
      itemBuilder: (context, index) {

        if (index < _books.length) {
          return _books[index];
        }
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: _buildShelf(),
      floatingActionButton: new FloatingActionButton(
          onPressed: _addBook,
        tooltip: 'Add task',
        child: new Icon(Icons.add)
      ),
    );
  }

}