import 'package:flutter/material.dart';
import 'book.dart';

// Generalized widget for rendering all the required books

class Shelf extends StatefulWidget {
  @override
  createState() => new ShelfState();
}

class ShelfState extends State<Shelf> {

  List<Book> _books = [];

  void _addBook(String bookName, String bookAuthor) {
    //SetState() will rerender the Shelf
    setState(() {
      int index = _books.length;
      _books.add(new Book(bookName, bookAuthor)); // Autogenerated Test Data
    });
  }

  Widget _buildShelf() {
    return new ListView.builder(
      // ignore: missing_return
      itemBuilder: (context, index) {

        if (index < _books.length) {
          return _books[index];
        }
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: _buildShelf(),
      floatingActionButton: new FloatingActionButton(
          onPressed: _pushAddBookScreen,
        tooltip: 'Add task',
        child: new Icon(Icons.add)
      ),
    );
  }

  void _pushAddBookScreen() {
    // Push the book add page onto the stack

    String title;
    String author;

    Navigator.of(context).push(
      new MaterialPageRoute(
        builder: (context) {
          return new Scaffold(
            appBar: new AppBar(
              title: new Text('Add New Book')
            ),
            body: new Column(
              children: <Widget> [
              new TextField(
              autofocus: true,
              onSubmitted: (val) {
                Navigator.pop(context);
              },
              decoration: new InputDecoration(
                  hintText: 'Book Title',
                  contentPadding: const EdgeInsets.all(16.0)
              ),
            ),
                new TextField(

                )
              ]
            )
          );
        }
      )
    );
  }

}