import 'package:flutter/material.dart';
import '../components/book.dart';
import '../services/fetchtitles.dart';
import 'package:http/http.dart' as http;

// Generalized widget for rendering all the required books

class Shelf extends StatefulWidget {
  @override
  createState() => new ShelfState();
}

class ShelfState extends State<Shelf> {

  List<Book> _books = [];

//  void _addBook(String bookName, List<String> bookAuthor) {
//    //SetState() will rerender the Shelf
//    setState(() {
//      int index = _books.length;
//      _books.add(new Book(bookName, bookAuthor)); // Autogenerated Test Data
//    });
//  }

  Widget _buildShelf() {
    return new GridView.builder(
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
      ),
      // ignore: missing_return
      itemBuilder: (context, index) {
        if (_books == null) {
          print("No Books Right now");
        }

        if (index < _books.length) {
          return _books[index];
        }
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: _buildShelf(),
      floatingActionButton: new FloatingActionButton(
          onPressed: _pushAddBookScreen,
        tooltip: 'Add Book',
        child: new Icon(Icons.add)
      ),
    );
  }

  void _renderResultsScreen(String val) {
    // Push book search results page onto the stack
    print("Reached 57: ${val}");
    Navigator.of(context).push(
      new MaterialPageRoute(
        builder: (context) {
          return new Scaffold(
            appBar: new AppBar(
              title: new Text('Results')
            ),
                body: FutureBuilder<List<Book>>(
                future: fetchBooks(val),
                  builder: (context, snapshot) {
                    print("Ths is the snapshot:");
                    print(snapshot);
                    if (snapshot.connectionState == ConnectionState.none &&
                        snapshot.hasData == null) {
                      //print('project snapshot data is: ${projectSnap.data}');
                      return Container();
                    }
                    return ListView.builder(
                      itemCount: snapshot.data.length,
                      itemBuilder: (context, index) {
                        Book book = snapshot.data[index];
                        return Column(
                          children: <Widget>[
                            // Widget to display the list of project
                          ],
                        );
                      },
                    );
                  },
              )
            );
          }
        )
      );
    }

  void _pushAddBookScreen() {
    // Push the book add page onto the stack
    print("REACHED 95");
    Navigator.of(context).push(
      new MaterialPageRoute(
        builder: (context) {
          return new Scaffold(
            appBar: new AppBar(
              title: new Text('Add New Book')
            ),
            body: new Column(
              children: <Widget> [
              new TextField(
              autofocus: true,
              onSubmitted: (val) {
                _renderResultsScreen(val);
              },
              decoration: new InputDecoration(
                  hintText: 'Book Title',
                  contentPadding: const EdgeInsets.all(16.0)
              ),
            )
              ]
            )
          );
        }
      )
    );
  }
}

//class BooksList extends StatelessWidget {
//  final List<Book> books;
//
//  BooksList({Key key, this.books}) : super(key: key);
//
//  @override
//  Widget build(BuildContext context) {
//    return ListView.builder(
//      // ignore: missing_return
//      itemBuilder: (context, index) {
//        if (index < books.length) {
//          final bookWidget =
//          return bookWidget;
//        }
//      }
//    );
//  }
//}